### ISSUE TITLE
Data Set

### ISSUE THREAD

**Issue by uMklami** [MichalDanielDobrzanski/DeepLearningPython35#3]
Dear Concern,

I am trying to see the data structure inside the .pkl file but i couldn't get until. can you tell me that what type of data is inside this file. as i want to run your example on .csv data. Thanks in advance!

**Comment by MichalDanielDobrzanski** [comment]
Hello,

I apologize for my late reply - I had lots of changes with my university and work.

The .pkl file examination is out of the scope of this testing script.
I only imported that loading data script from sample code from Mr. Nielsen. For example `load_data_shared()` in: [https://github.com/mnielsen/neural-networks-and-deep-learning/blob/master/src/network3.py](https://github.com/mnielsen/neural-networks-and-deep-learning/blob/master/src/network3.py)

The purpose of this testing script is to be compatible with Python3.5.2

If you have found solution in order to import custom CSV data, please let me know.

But, at the end, I have written my Master Thesis with the help of **Keras** and **pandas** libraries for prototyping networks and feeding them with CSV data.

**Comment by BriFuture** [comment]
Hi.
I meet a similar problem: I want to load mnist data from downloaded file which is downloaded from offical website of http://yann.lecun.com/exdb/mnist/, but when running the code provided by Mr.Nielsen (https://github.com/mnielsen/neural-networks-and-deep-learning/blob/master/src/network.py), it seems  
that something wrong with the code because accuracy is as low as about 1000/10000 (or 10%)

But When I try the sample code with data loaded from the pickle file, everything seems fine and the accuracy will reach more than 90%.
I found that there is some differences between the data loaded from pickle file and original file , but when I draw some picture from them within a plot, the two images seemed similar with each other:
![image](https://user-images.githubusercontent.com/7582298/50877648-c7291700-140d-11e9-99af-5ec8e736084d.png)
Left Image is plotted with data from pickle file, the right one is plotted with data from original file

As we can see, both images look like the same, but actually gray scales at some pixels in these two images are not the same.

Thank you.

**Comment by BriFuture** [comment]
Sorry,  I found that the problem is caused by my coding error:
the test data generated from official website mixed labels with wrong Images during wrapper process when coding.
